import type { ReactNode } from "react";
import { SYNTHETIC_NOTICE } from "@/lib/engines/documents/pools";

/** Prominent label shown on every generated document, on screen and in print. */
export function SyntheticBanner() {
  return (
    <p
      className="mb-6 rounded-lg border-2 border-dashed border-warn/60 bg-warn-soft px-3 py-2 text-center text-xs font-bold tracking-widest text-warn uppercase print:border-black print:bg-white print:text-black"
      role="note"
    >
      {SYNTHETIC_NOTICE}
    </p>
  );
}

function Watermark() {
  return (
    <div aria-hidden="true" className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden">
      <span className="rotate-[-28deg] font-display text-[5.5rem] leading-none font-bold whitespace-nowrap text-navy/[0.045] select-none print:text-black/[0.06]">
        SYNTHETIC · TEST DATA
      </span>
    </div>
  );
}

/** Generic monogram — generated documents never use logos. */
export function Monogram({ name }: { name: string }) {
  const initials = name
    .replace(/[^A-Za-z ]/g, "")
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0].toUpperCase())
    .join("");
  return (
    <span
      aria-hidden="true"
      className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-navy font-display text-sm font-bold text-paper print:border print:border-black print:bg-white print:text-black"
    >
      {initials || "SD"}
    </span>
  );
}

export function DocumentPaper({ children, label }: { children: ReactNode; label: string }) {
  return (
    <article
      aria-label={label}
      className="print-page relative mx-auto max-w-3xl overflow-hidden rounded-2xl border border-line bg-white p-6 text-sm text-ink shadow-sm sm:p-10 print:max-w-none print:rounded-none print:p-0"
    >
      <Watermark />
      <div className="relative">
        <SyntheticBanner />
        {children}
        <p className="mt-8 border-t border-line pt-3 text-center text-[11px] text-muted print:text-black">
          {SYNTHETIC_NOTICE}. Generated by Zero Real for testing only. All names, numbers and addresses are
          invented.
        </p>
      </div>
    </article>
  );
}
